<a href="<?=App::config('url')?>farm/details" 
class="success button expanded">New farm</a>
<div class="grid-x grid-padding-x">
    <?php foreach($farms as $farm):?>

        <div class="large-3 medium-6 cell">
            <div class="callout" style="text-align: center;">
                <img src="<?=App::config('url')?>public/img/farm/farm1.jpg" 
                alt="<?=$farm->name?>">
                <h1 class="farmName">
                    <?=$farm->name?>
                </h1>
                <div class="success callout">
                    <a href="<?=App::config('url')?>farm/details/<?=$farm->id?>">
                            <i title="Change" class="fas fa-2x fa-pencil-alt"></i>
                        </a>
                        <?php if($farm->pig==0): ?>
                        <a 
                        onclick="return confirm('Sigurno obrisati predavača &#34;<?=$farm->name?>&#34;?');"
                        href="<?=App::config('url')?>farm/delete/<?=$farm->id?>">
                            <i title="Delete" style="color: red; margin-left: 20px;" class="fas fa-2x fa-trash-alt"></i>
                        </a>
                        <?php else:?>
                            <i title="Can not be deleted because farm has pigs(<?=$farm->pig?>)" style="color: gray; margin-left: 20px;" class="fas fa-2x fa-trash-alt"></i>
                        <?php endif;?>
                </div>
                
            </div>
            
        </div>

    <?php endforeach;?>
    <div class="large-3 medium-6 cell">
            <div class="callout" style="text-align: center;">
                <img src="<?=App::config('url')?>public/img/farm/farm2.jpg" 
                alt="">
                <h1 class="farmName">
                <a href="<?=App::config('url')?>farm/details" class="">New farm</a>

                </h1>
                <div class="success callout">
                     <i style="color: gray; margin-left: 20px;" class="fas fa-2x fa-pencil-alt"></i>
                       
                            <i  style="color: gray; margin-left: 20px;" class="fas fa-2x fa-trash-alt"></i>
                      
                </div>
                
            </div>
            
        </div>
</div>





