<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> OPG Zapisnik </title>
    <link rel="stylesheet" href="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
  </head>
  <body>

    <!-- Start Top Bar -->
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text"> Dobrodošli 🚜 </li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><a href="#">Prijavi se</a></li>
        </ul>
      </div>
    </div>
    <!-- End Top Bar -->

    <div class="callout large">
      <div class="row column text-center">
        <h1>OPG Zapisnik</h1>
        <p class="lead"> Ova stranica namijenjena je za obiteljska poljoprivredna gospodarstva koja trebaju pomoć pri vođenju vlastitog gospodarstva. </br>
                         Nakon što se ulogirate, možete zapisnik svoja obradiva zemljišta, mehanizaciju, radnike, sredstva za zaštitu i kulture koje obrađujete.   </p>
        <a href="https://www.zakon.hr/z/1015/Zakon-o-obiteljskom-poljoprivrednom-gospodarstvu" class="button large" target="_blank">Zakon o OPG-u</a>
        <a href="https://ips-konzalting.hr/blog/ips-novosti-8/post/koraci-i-dokumentacija-za-otvaranje-opg-a-382" class="button large hollow" target="_blank">Kako otvoriti OPG</a>
      </div>
    </div>

    <div class="row">
      <div class="medium-4 columns">
        <h3><a href="https://ruralnirazvoj.hr/" target="_blank"> Program ruralnog razvoja </a></h3>
        <p class="with-eight">
          Programa ruralnog razvoja, dana 26. svibnja 2015. godine Europska komisija je odobrila Program ruralnog razvoja Republike Hrvatske za razdoblje 2014. – 2020. Odluka o odobrenju predstavlja krunu tog dugotrajnog procesa u koji su bili uključeni domaći stručnjaci, mahom djelatnici Ministarstva poljoprivrede i Agencije za plaćanja u poljoprivredi, ribarstvu i ruralnom razdoblju. </br>
          Program ruralnog razvoja RH za razdoblje 2014. – 2020. vrijedan oko 2.4 milijarde EUR-a, dosada je doživio devet izmjena. </br>
          Programom je definirano 19 mjera koje imaju za cilj povećanje konkurentnosti hrvatske poljoprivrede, šumarstva i prerađivačke industrije, ali i unaprjeđenja životnih i radnih uvjeta u ruralnim područjima uopće. </br>
        </p>
      </div>

      <div class="medium-4 columns">
        <h3><a href="https://eurokonzalting.com/" target="_blank"> Eurokonzalting </a></h3>
        <p>
          Web stranica namijenjena je Vama s namjerom pružanja kvalitetnih i korisnih informacija u svezi planiranja, organiziranja i realizacije ciljeva vašeg poslovanja, ishođenja bespovratnih sredstava iz nacionalnih izvora i EU fondova. </br>
          Portal koji čini sastavni dio stranice ima za cilj, uz informativni karakter, promovirati uspješne poduzetničke projekte i projekte javne uprave koji su realizirani kao rezultat ljudske upornosti, znanja i iskustva, kreativnosti i mašte. </br>
        </p>
      </div>
      <div class="medium-4 columns">
        <h3><a href="https://www.apprrr.hr/" target="_blank"> APPRRR </a></h3>
        <p class="with-eight">

          Agencija za plaćanja u poljoprivredi, ribarstvu i ruralnom razvoju je javno tijelo nadležno za operativnu provedbu mjera izravne potpore, mjera ruralnog razvoja, mjera za pomorstvo i ribarstvo (u dijelu delegiranih funkcija) i mjera zajedničke organizacije tržišta, </br> kao i vođenje upisnika i registara te održavanje i korištenje Integriranog administrativnog i kontrolnog sustava (IAKS-a) preko kojeg se zaprimaju,
         </br> obrađuju i kontroliraju izravna plaćanja poljoprivrednicima.
        </p>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>


  </body>
</html>



