<a href="<?=App::config('url')?>pig/details"
class="success button expended"> New pig</a>
<from method="GET"
action="<?=App::config('url')?>pig/index">
    <input type="text" name="conditon" placeholder="farm,breed or weight"
    value="<?=$condition?>">
</from>
<?php include 'paging.phtml' ?>
<div class="grid-x grid-padding-x">
    <?php foreach($pigs as $pig):?>

        <div class="large-3 medium-6 cell">
            <div class="callout" style="text-align: center;">
                <img src="<?=App::config('url')?>public/img/pig/welsh.png"
                alt="<?=$pig->breed?> <?$pig->gender?>">
                <h1 class="farmName">
                    <?=$pig->breed?> <?$pig->gender?>
                </h1>
                <div class="sucess callout">
                     <a href="<?=App::config('url')?>pig/details/<?=$pig->id?>">
                        <i title ="Change" class="fas fa-2x fa-pencil-alt"></i>
                        </a>
                        <?php if ($pig->farm==0): ?>
                        <a
                        onclick="return confirm('Are you sure you want to delete the pig &#34;<?=$pig->breed?> <?$pig->gender?>&#34;?');"
                        href="<?=App::config('url')?>pig/delete/<?=$pig->id?>">
                            <i title="Delete" style="color: red; margin-left: 20px;" class="fas fa-2x fa-trash-alt"></i>
                        </a>
                        <?php else:?>
                            <i title="Can not be deleted because it belongs to a farm(<?=$pig->farm?>)" style="color: gray; margin-left: 20px;" class="fas fa-2x fa-trash-alt"></i>
                        <?php endif;?>
                </div>  
            </div>
        </div>
    <?php endforeach;?>
    <?php include 'paging.phtml' ?>
</div>