<a href="<?=App::config('url')?>pig/details"
class="success button expended"> New pig</a>
<from method="GET"
action="<?=App::config('url')?>pig/index">
    <input type="text" name="conditon" placeholder="farm,breed or weight"
    value="<?=$condition?>">
</from>
<?php include 'paging.phtml' ?>
<div class="grid-x grid-padding-x">
    <?php foreach($pigs as $pig):?>

        <div class="large-3 medium-6 cell">
            <div class="callout" style="text-align: center;">
          
            









            <?php else:?>
                            <i title="Ne može se obrisati jer sudjeluje na grupama(<?=$polaznik->grupa?>)" style="color: gray; margin-left: 20px;" class="fas fa-2x fa-trash-alt"></i>
            <?php endif;?>
                </div>  
            </div>
        </div>
    <?php endforeach;?>
    <?php include 'paging.phtml' ?>
</div>